import type { Metadata } from "next";
// import { useState } from "react";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
// import Header from "./Component/Header";
// import Sidebar from "./Component/sidebar";
// import Login from "./Component/Login";
// import ClientLayout from "./Component/ClientLayout";
import Header from "./Component/Header";
import Sidebar from "./Component/sidebar";
import { AuthProvider } from "@/lib/AuthContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Work Flow",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      <body className="h-full">
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  );
}
